version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Montreal
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.34.0
